package com.uf.fanfan.entity;

// Generated 2013-10-10 21:40:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private long id;
	private CustomerOrder customerOrder;
	private int productid;
	private Float tradeprice;
	private int tradeAmount;
	private Date tradetime;
	private String evaluation;

	public OrderDetail() {
	}

	public OrderDetail(long id, CustomerOrder customerOrder, int productid,
			int tradeAmount, Date tradetime) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.productid = productid;
		this.tradeAmount = tradeAmount;
		this.tradetime = tradetime;
	}

	public OrderDetail(long id, CustomerOrder customerOrder, int productid,
			Float tradeprice, int tradeAmount, Date tradetime, String evaluation) {
		this.id = id;
		this.customerOrder = customerOrder;
		this.productid = productid;
		this.tradeprice = tradeprice;
		this.tradeAmount = tradeAmount;
		this.tradetime = tradetime;
		this.evaluation = evaluation;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public Float getTradeprice() {
		return this.tradeprice;
	}

	public void setTradeprice(Float tradeprice) {
		this.tradeprice = tradeprice;
	}

	public int getTradeAmount() {
		return this.tradeAmount;
	}

	public void setTradeAmount(int tradeAmount) {
		this.tradeAmount = tradeAmount;
	}

	public Date getTradetime() {
		return this.tradetime;
	}

	public void setTradetime(Date tradetime) {
		this.tradetime = tradetime;
	}

	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

}
