package com.uf.fanfan.entity;

// Generated 2013-10-10 21:40:33 by Hibernate Tools 3.4.0.CR1

/**
 * Agent generated by hbm2java
 */
public class Agent implements java.io.Serializable {

	private int id;
	private String name;
	private String password;
	private String address;
	private String phoneNum;
	private Float balance;
	private Float backMoney;
	private String realName;

	public Agent() {
	}

	public Agent(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Agent(int id, String name, String password, String address,
			String phoneNum, Float balance, Float backMoney, String realName) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.address = address;
		this.phoneNum = phoneNum;
		this.balance = balance;
		this.backMoney = backMoney;
		this.realName = realName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	public Float getBackMoney() {
		return this.backMoney;
	}

	public void setBackMoney(Float backMoney) {
		this.backMoney = backMoney;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

}
