package com.uf.fanfan.entity;

// Generated 2013-10-10 21:40:33 by Hibernate Tools 3.4.0.CR1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private int id;
	private String name;
	private String password;
	private Float balance;
	private Float totalConsume;
	private Integer agentid;

	public Customer() {
	}

	public Customer(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Customer(int id, String name, String password, Float balance,
			Float totalConsume, Integer agentid) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.balance = balance;
		this.totalConsume = totalConsume;
		this.agentid = agentid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	public Float getTotalConsume() {
		return this.totalConsume;
	}

	public void setTotalConsume(Float totalConsume) {
		this.totalConsume = totalConsume;
	}

	public Integer getAgentid() {
		return this.agentid;
	}

	public void setAgentid(Integer agentid) {
		this.agentid = agentid;
	}

}
