package com.uf.fanfan.entity;

// Generated 2013-10-10 21:40:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.uf.fanfan.common.TradeState;

/**
 * CustomerOrder generated by hbm2java
 */
public class CustomerOrder implements java.io.Serializable {

	private long id;
	private Customer customer;
	private Date arrivetime;
	private TradeState tradestate;
	private Float sumMoney;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public CustomerOrder() {
	}
	public String toString(){
		return  "{订单id:"+id+";客户id:"+customer.getId()+";送达时间："+arrivetime.toString()+"}";
	}
	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getArrivetime() {
		return this.arrivetime;
	}

	public void setArrivetime(Date arrivetime) {
		this.arrivetime = arrivetime;
	}

	public TradeState getTradestate() {
		return this.tradestate;
	}

	public void setTradestate(TradeState tradestate) {
		this.tradestate = tradestate;
	}

	public Float getSumMoney() {
		return this.sumMoney;
	}

	public void setSumMoney(Float sumMoney) {
		this.sumMoney = sumMoney;
	}

	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}
	
}
