package com.uf.fanfan.entity;

// Generated 2013-10-10 21:40:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerOrder generated by hbm2java
 */
public class CustomerOrder implements java.io.Serializable {

	private long id;
	private int customerid;
	private Date arrivetime;
	private Short tradestate;
	private Float sumMoney;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public CustomerOrder() {
	}

	public CustomerOrder(long id, int customerid, Date arrivetime) {
		this.id = id;
		this.customerid = customerid;
		this.arrivetime = arrivetime;
	}

	public CustomerOrder(long id, int customerid, Date arrivetime,
			Short tradestate, Float sumMoney, Set<OrderDetail> orderDetails) {
		this.id = id;
		this.customerid = customerid;
		this.arrivetime = arrivetime;
		this.tradestate = tradestate;
		this.sumMoney = sumMoney;
		this.orderDetails = orderDetails;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	public Date getArrivetime() {
		return this.arrivetime;
	}

	public void setArrivetime(Date arrivetime) {
		this.arrivetime = arrivetime;
	}

	public Short getTradestate() {
		return this.tradestate;
	}

	public void setTradestate(Short tradestate) {
		this.tradestate = tradestate;
	}

	public Float getSumMoney() {
		return this.sumMoney;
	}

	public void setSumMoney(Float sumMoney) {
		this.sumMoney = sumMoney;
	}

	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
