package com.uf.fanfan.entity;

// Generated 2013-10-10 21:40:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.uf.fanfan.common.ProductState;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int id;
	private Shop shop;
	private String name;
	private String description;
	private Double price;
	private Date createTime;
	private Integer saleSum;
	private ProductState state;

	public Product() {
	}

	public Product(int id, String name, Date createTime) {
		this.id = id;
		this.name = name;
		this.createTime = createTime;
	}

	public Product(int id, Shop shop, String name, String description,
			Double price, Date createTime, Integer saleSum, ProductState state) {
		this.id = id;
		this.shop = shop;
		this.name = name;
		this.description = description;
		this.price = price;
		this.createTime = createTime;
		this.saleSum = saleSum;
		this.state = state;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getSaleSum() {
		return this.saleSum;
	}

	public void setSaleSum(Integer saleSum) {
		this.saleSum = saleSum;
	}

	public ProductState getState() {
		return this.state;
	}

	public void setState(ProductState state) {
		this.state = state;
	}

}
