package com.uf.fanfan.entity;

// Generated 2013-10-10 21:40:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Tradedetail generated by hbm2java
 */
public class TradeDetail implements java.io.Serializable {

	private long id;
	private int productid;
	private int customerid;
	private Date tradetime;
	private Short tradestate;
	private Float tradeprice;
	private String evaluation;

	public TradeDetail() {
	}

	public TradeDetail(long id, int productid, int customerid, Date tradetime) {
		this.id = id;
		this.productid = productid;
		this.customerid = customerid;
		this.tradetime = tradetime;
	}

	public TradeDetail(long id, int productid, int customerid, Date tradetime,
			Short tradestate, Float tradeprice, String evaluation) {
		this.id = id;
		this.productid = productid;
		this.customerid = customerid;
		this.tradetime = tradetime;
		this.tradestate = tradestate;
		this.tradeprice = tradeprice;
		this.evaluation = evaluation;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	public Date getTradetime() {
		return this.tradetime;
	}

	public void setTradetime(Date tradetime) {
		this.tradetime = tradetime;
	}

	public Short getTradestate() {
		return this.tradestate;
	}

	public void setTradestate(Short tradestate) {
		this.tradestate = tradestate;
	}

	public Float getTradeprice() {
		return this.tradeprice;
	}

	public void setTradeprice(Float tradeprice) {
		this.tradeprice = tradeprice;
	}

	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

}
